"""
Notes Agent — creates structured incident notes via MCP Notes server.
"""
from app.tools.db_tools import save_note
from app.tools.mcp_client import call_mcp_tool


async def create_note(incident: dict, log_data: dict) -> dict:
    content = (
        f"Incident {incident['id']} auto-generated by AI Copilot.\n"
        f"Error: {incident['error']}\n"
        f"Severity: {incident['severity']}\n"
        f"Summary: {incident.get('summary','')}\n"
        f"Analysis mode: {log_data.get('mode','fallback')}\n"
        + (f"Suggested action: {log_data.get('suggested_action','')}" if log_data.get('suggested_action') else "")
    ).strip()

    tags = f"severity:{incident['severity'].lower()},auto-generated"

    result = await call_mcp_tool(
        "create_incident_note",
        incident_id=incident["id"],
        content=content,
        author="AI-Copilot",
        tags=tags,
    )

    if "mcp_error" not in result:
        save_note(result)
        return result

    # Fallback
    import uuid
    note = {
        "note_id":     f"NOTE-{str(uuid.uuid4())[:6].upper()}",
        "incident_id": incident["id"],
        "content":     content,
        "author":      "AI-Copilot",
        "tags":        tags,
    }
    save_note(note)
    return note
